---
environment:
  winrm_user: test_user
  winrm_pass: Pass@word1
  winrm_port: 5985
  matrix:
    - suite: default-windows
    - suite: uninstall-windows

install:
  - net user /add %winrm_user% %winrm_pass%
  - net localgroup administrators %winrm_user% /add
  - choco install -y chefdk --version 2.0.28
  - refreshenv
  - set KITCHEN_YAML=.kitchen.appveyor.yml
  - chef gem install kitchen-local kitchen-pester

build: off

test_script:
  - chef exec kitchen converge %suite%
  - chef exec kitchen verify %suite%

deploy: off
