---
driver:
  name: docker
  privileged: true

provisioner:
  name: chef_solo
  chef_license: accept

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
    driver_config:
      run_command: /sbin/init
  - name: ubuntu-20.04
    driver_config:
      run_command: /sbin/init
  - name: centos-7.2
    driver_config:
      run_command: /usr/sbin/init
      provision_command: yum install -y initscripts

suites:
  - name: default
    run_list:
      - recipe[code_deploy]
  - name: uninstall
    run_list:
      - recipe[code_deploy]
      - recipe[code_deploy::uninstall_agent]

verifier:
  name: inspec
