---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  chef_license: accept

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-18.04
  - name: ubuntu-20.04
  - name: centos-8.4
  - name: mwrock/Windows2016
    transport:
      name: winrm

suites:
  - name: default
    run_list:
      - recipe[code_deploy]
  - name: uninstall
    run_list:
      - recipe[code_deploy]
      - recipe[code_deploy_test::uninstall_agent]

verifier:
  name: inspec
