---
driver:
  name: local

platforms:
  - name: windows

transport:
  name: winrm
  hostname: localhost
  username: <%= ENV['winrm_user'] %>
  password: <%= ENV['winrm_pass'] %>
  port: <%= ENV['winrm_port'] %>

provisioner:
  name: chef_solo
  chef_license: accept

suites:
  - name: default
    run_list:
      - recipe[code_deploy]
  - name: uninstall
    run_list:
      - recipe[code_deploy]
      - recipe[code_deploy_test::uninstall_agent]

verifier:
  name: inspec
