sudo: required
language: ruby
rvm:
  - 3.0.1
services:
  - docker
script:
  - |
    if [ $SUITE != unit ]; then
      KITCHEN_YAML=.kitchen.docker.yml bundle exec kitchen test $SUITE
    fi
  - |
    if [ $SUITE = unit ]; then
      bundle exec rspec
    fi
deploy:
  provider: script
  script: openssl aes-256-cbc -K $encrypted_ecb18825a7dd_key -iv $encrypted_ecb18825a7dd_iv -in .supermarket.pem.enc -out .supermarket.pem -d && rvm $TRAVIS_RUBY_VERSION do bundle exec stove login --username meringu --key .supermarket.pem && rvm $TRAVIS_RUBY_VERSION do bundle exec stove --no-git
  on:
    tags: true
    condition: $SUITE = unit
  skip_cleanup: true
env:
  - SUITE=unit
  - SUITE=default-centos-79
  - SUITE=default-ubuntu-1404
  - SUITE=default-ubuntu-1604
  - SUITE=default-ubuntu-1804
  - SUITE=default-ubuntu-2004
  - SUITE=uninstall-centos-79
  - SUITE=uninstall-ubuntu-1404
  - SUITE=uninstall-ubuntu-1604
  - SUITE=uninstall-ubuntu-1804
  - SUITE=uninstall-ubuntu-2004
